import { baseURL } from "@/components/baseURL";
import AllCoursesComponents from "./AllCoursesComponents";
export const metadata = {
  title: "Skill Sphere   -Courses",
  description: "Generated by create next app",
};

const CoursesPage = () => {
  const AllCoursePromise = fetch(baseURL, { cache: "no-store" }).then((res) =>
    res.json(),
  );
  return (
    <section className="w-full max-w-7xl mx-auto px-5">
      <h1 className="text-2xl md:text-5xl font-bold">
        All <span className="text-blue-500">Courses</span>
      </h1>
      <AllCoursesComponents AllCoursePromise={AllCoursePromise} />
    </section>
  );
};

export default CoursesPage;
