import LoginCliComponents from "./LoginCliComponents";

export const metadata = {
  title: "Skill Sphere   -Login",
  description: "Generated by create next app",
};
const LoginPage = () => {

  return (
    <section className="w-full max-w-7xl flex justify-center mx-auto px-5 h-screen">
      <div className="loginForm w-max px-5 flex flex-col h-max items-center border border-blue-500 py-5 rounded-xl">
        <h1 className="text-2xl md:text-5xl font-bold">Login Now</h1>
       <LoginCliComponents />
      </div>
    </section>
  );
};

export default LoginPage;
