import React from "react";
import ProfileCLIComponent from "./ProfileCLIComponent";
export const metadata = {
  title: "Skill Sphere   -Profile",
  description: "Generated by create next app",
};

const ProfilePage = () => {
  return (
    <section className="w-full max-w-7xl mx-auto px-5 flex items-center justify-center">
      <div className="profile">
        <h1 className="text-2xl text-center">User profile</h1>

       <ProfileCLIComponent />
      </div>
    </section>
  );
};

export default ProfilePage;
